{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "p2p-vpn.fullname" . }}
  labels:
    {{- include "p2p-vpn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dataKey }}
  data.key: {{ .Values.secrets.dataKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.identityKey }}
  identity.key: {{ .Values.secrets.identityKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.caPubKey }}
  ca.pub: {{ .Values.secrets.caPubKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.nodeSig }}
  node.sig: {{ .Values.secrets.nodeSig | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.allowedPeers }}
  whitelist.txt: {{ .Values.secrets.allowedPeers | b64enc | quote }}
  {{- end }}
{{- end }}
